tnzerox:
  name: molla
  config:
    -
      name: General
      type: group
      items:
        -
          name: Logo
          type: image
          options: {  }
          id: logo
        -
          name: Footer_Logo
          type: image
          options: {  }
          id: footer_logo
        -
          name: Favicon
          type: image
          options: {  }
          id: favicon

    -
      name: Slider
      type: group
      items:
        -
          name: Slider
          id: slider
          type: bootstrap_collection
          options:
            allow_add: true
            allow_delete: true
            template:
              - { name: 'Slide Image', type: image, id: slide_image }
              - { name: 'Slide Caption Title', type: text, id: slide_caption_title }
              - { name: 'Slide Caption Intro', type: text, id: slide_caption_intro }
              - { name: 'Slide Price', type: text, id: slide_price }
              - { name: 'Button text', type: url, id: slide_button_text }
              - { name: 'Button Link', type: url, id: slide_button_link }

    -
      name: 'Explore Popular Products'
      type: group
      items:
        -
          name: 'Popular Collection'
          type: bootstrap_collection
          options:
            allow_add: true
            allow_delete: true
            template:
              - { name: Name, type: text, id: name }
              - { name: Collection, type: collection_select, options: { multiple: false }, id: collection }
          id: popular_collection

    -
      name: Offer Card
      type: group
      items:
        - name: Offer Card
          id: offer_cart
          type: bootstrap_collection
          options:
            allow_add: true
            allow_delete: true
            template:
              - { name: 'Image', type: image, id: image }
              - { name: 'Title', type: text, id: title }
              - { name: 'Description', type: text, id: description }
              - { name: 'Button text', type: url, id: button }
              - { name: 'Button Link', type: url, id: link }

    - name: 'Collection Gallery'
      type: group
      items:
        - name: 'Collection Gallery'
          type: bootstrap_collection
          options:
            allow_add: true
            allow_delete: true
            template:
              - { name: Name, type: text, id: name }
              - { name: Collection, type: collection_select, options: { multiple: true }, id: collection }
          id: collection_gallery

    -
      name: 'Banner Design'
      type: group
      items:
        -
          name: 'Banner Design'
          type: bootstrap_collection
          options:
            allow_add: true
            allow_delete: true
            template:
              - { name: 'Image', type: image, id: image }
              - { name: 'Title', type: text, id: title }
              - { name: 'Description', type: text, id: description }
              - { name: 'Button text', type: url, id: button }
              - { name: 'Button Link', type: url, id: link }
          id: banner_design

    -
      name: 'Recommended Product'
      type: group
      items:
        -
          name: 'Recommended Product'
          type: bootstrap_collection
          options:
            allow_add: true
            allow_delete: true
            template:
              - { name: Name, type: text, id: name }
              - { name: Collection, type: collection_select, options: { multiple: false }, id: collection }
          id: recommended_product

    - name: 'Trending Collection'
      type: group
      items:
        - name: 'Trending Collection'
          type: bootstrap_collection
          options:
            allow_add: true
            allow_delete: true
            template:
              - { name: Name, type: text, id: name }
              - { name: 'Image', type: image, id: image }
              - { name: Collection, type: collection_select, options: { multiple: true }, id: collection }
          id: trending_collection
    -
      name: Bottom Card
      type: group
      items:
        - name: Bottom Card
          id: bottom_card
          type: bootstrap_collection
          options:
            allow_add: true
            allow_delete: true
            template:
              - { name: 'Image', type: image, id: image }
              - { name: 'Title', type: text, id: title }
              - { name: 'Description', type: text, id: description }
              - { name: 'Button text', type: url, id: button }
              - { name: 'Button Link', type: url, id: link }

    -
      name: 'Bottom Collection'
      type: group
      items:
        -
          name: 'Bottom Collection'
          type: bootstrap_collection
          options:
            allow_add: true
            allow_delete: true
            template:
              - { name: Name, type: text, id: name }
              - { name: Collection, type: collection_select, options: { multiple: false }, id: collection }
          id: bottom_collection

    -
      name: Social
      type: group
      items:
        -
          name: Facebookurl
          type: url
          options: {  }
          id: facebookUrl
        -
          name: Twitterurl
          type: url
          options: {  }
          id: twitterUrl
        -
          name: Pinteresturl
          type: url
          options: {  }
          id: pinterestUrl
        -
          name: Youtubeurl
          type: url
          options: {  }
          id: youtubeUrl
        -
          name: Instagramurl
          type: url
          options: {  }
          id: instagramUrl
        -
          name: Linkedinurl
          type: url
          options: {  }
          id: linkedinUrl

    -
      name: Contact
      type: group
      items:
        -
          name: Email
          type: email
          options: {  }
          id: email
        -
          name: 'Phone Number'
          type: text
          options: {  }
          id: phone_number
        -
          name: Address
          type: text
          options: {  }
          id: address
        -
          name: 'Copyright Text'
          type: text
          id: copyright_text
    -
      name: Menu
      type: group
      items:
        -
          name: 'Main Menu'
          type: menu_select
          options: {  }
          id: main_menu
        -
          name: 'Footer Menu 1'
          type: menu_select
          options: {  }
          id: footer_menu_1

        - name: 'Footer Menu 2'
          type: menu_select
          options: { }
          id: footer_menu_2

        -
          name: 'Pages Menu'
          type: menu_select
          options: {  }
          id: pages_menu
    -
      name: 'Payment icons'
      type: group
      items:
        -
          name: 'Payment Icons'
          type: bootstrap_collection
          options:
            allow_add: true
            allow_delete: true
            template: [{ name: Title, type: text, id: title }, { name: Image, type: image, id: image }, { name: Link, type: url, id: link }]
          id: payment_icons
      id: 'Payment icons'
